Change to multiple MAC in one BTDEVADDR
canonical/oem-qa-tools pull request #20
Opened 2023-05-24 08:29 UTC by hanhsuan

Since CQT-2031 has merged into checkbox and released  in 2.6, we could change the default palinbox.conf of oem-qa-tools to multiple MAC in one BTDEVADDR style.

2023-05-24 08:32 UTC, clairlin53 approved these changes
LGTM

2023-05-25 03:02 UTC, LiaoU3 requested changes

2023-05-25 03:02 UTC, LiaoU3 commented on Tools/PC/oem-qa-checkbox-installer/conf/plainbox.conf
>  # === Select one BTDEVADDR below ===
Maybe we don't need this line after we can automatically select bluetooth address?

2023-05-25 03:02 UTC, LiaoU3 commented on Tools/PC/oem-qa-checkbox-installer/conf/plainbox.conf
>  # ==================================
And also this line.

2023-05-25 03:11 UTC, LiaoU3 commented on Tools/PC/oem-qa-checkbox-installer/conf/plainbox.conf
> +BTDEVADDR = 7C:B2:7D:4B:14:95,28:3A:4D:46:79:C0,34:6F:24:A8:93:EE,80:32:53:D8:0D:1E
@hanhsuan Quick question, is this address `80:32:53:D8:0D:1E` the new one?

2023-05-25 03:16 UTC, hanhsuan commented on Tools/PC/oem-qa-checkbox-installer/conf/plainbox.conf
> +BTDEVADDR = 7C:B2:7D:4B:14:95,28:3A:4D:46:79:C0,34:6F:24:A8:93:EE,80:32:53:D8:0D:1E
That is the Lab-office one

2023-05-25 03:35 UTC, LiaoU3 approved these changes
LGTM <3

2023-05-25 03:36 UTC, merged