Add markdown linter
canonical/oem-qa-tools pull request #21
Opened 2023-05-25 07:21 UTC by hanhsuan

Use markdownlint-cli2 to check Markdown content by github action, and fix errors that be found by markdownlint-cli2.

2023-05-25 07:51 UTC, LiaoU3 requested changes

2023-05-25 07:51 UTC, LiaoU3 commented on Tools/PC/oem-qa-checkbox-installer/conf/plainbox.conf
Why is this PR change this again?

2023-05-25 07:52 UTC, LiaoU3 requested changes

2023-05-25 07:52 UTC, LiaoU3 commented on Tools/PC/oem-qa-checkbox-installer/conf/plainbox.conf
> +BTDEVADDR = 7C:B2:7D:4B:14:95,28:3A:4D:46:79:C0,34:6F:24:A8:93:EE,80:32:53:D8:0D:1E
Why is this PR change this again?

2023-05-25 12:17 UTC, hanhsuan commented on Tools/PC/oem-qa-checkbox-installer/conf/plainbox.conf
> +BTDEVADDR = 7C:B2:7D:4B:14:95,28:3A:4D:46:79:C0,34:6F:24:A8:93:EE,80:32:53:D8:0D:1E
I have fixed that I checkout from non-main branch.

2023-05-26 00:51 UTC, baconYao approved these changes
LGTM

2023-05-29 02:28 UTC, stanley31huang commented
@hanhsuan  we have highlight bash/shell commands in markdown files with different alias, likes sh, bash, shell.
will they all present one command style?

2023-05-29 05:40 UTC, hanhsuan commented
@stanley31huang I've changed `shell/bash/sh` to the same alias `sh`

2023-05-31 02:10 UTC, stanley31huang commented on Tools/PC/jira-card-creator/README.md
> +source setup.sh
@hanhsuan  I think the original purpose is tell user to execute this command in shell terminal. so could you please add the "$" character back?

2023-05-31 02:39 UTC, hanhsuan commented on Tools/PC/jira-card-creator/README.md
> +source setup.sh
@stanley31huang this is an [issue](https://github.com/DavidAnson/markdownlint/blob/5a4cf179c42646a0ad48c3f9522fe324849d73ba/doc/md014.md) found by linter. If this is must have, I could add comment to ignore it.

2023-05-31 08:08 UTC, stanley31huang approved these changes
this PR is ready to merge.

2023-05-31 08:08 UTC, merged