Improve hardware transfer procedure
canonical/oem-qa-tools pull request #25
Opened 2023-06-16 01:37 UTC by baconYao

1. Rename jira_card_handler as cqt_handler
2. Move cqt_handler and cert_team_google_sheet_handler to handlers folder
3. Add c3_hanlder, telops_handler, notifier and hic_handler
4. Update procedure in main.py

No matter the procedure is handled by QA or Contractor, there's always need cards to be created in TELOPS board.

2023-06-19 00:45 UTC, hanhsuan requested changes

2023-06-19 00:45 UTC, hanhsuan commented on Tools/PC/transfer-hw-to-cert/handlers/c3_handler.py
> +        print('Updating {}'.format(dut['cid']))
Is there any reason to use old style to format  string ? The [f-Strings](https://realpython.com/python-f-strings/) would be easier to read.

2023-06-19 02:12 UTC, baconYao commented on Tools/PC/transfer-hw-to-cert/handlers/c3_handler.py
> +        print('Updating {}'.format(dut['cid']))
No any special reason, it's just I used to it.

Another reason is that I prefer single quotation mark than double quotation mark, therefore, the problem `SyntaxError: invalid syntax` bothers me if I use f-Strings.

- ref: https://realpython.com/python-f-strings/#dictionaries

2023-06-19 08:44 UTC, hanhsuan commented on Tools/PC/transfer-hw-to-cert/handlers/c3_handler.py
> +        print('Updating {}'.format(dut['cid']))
However, there are some others use f-string in your code. @stanley31huang  Do we need a role for string format?

2023-06-20 00:55 UTC, LiaoU3 commented on Tools/PC/transfer-hw-to-cert/handlers/c3_handler.py
> +        print('Updating {}'.format(dut['cid']))
I support fstring. It’s the future!

2023-07-05 15:02 UTC, baconYao commented on Tools/PC/transfer-hw-to-cert/handlers/c3_handler.py
> +        print('Updating {}'.format(dut['cid']))
Hi @hanhsuan, I update all the format string to be f-string, please review it

2023-07-06 00:38 UTC, hanhsuan approved these changes
LGTM

2023-07-12 06:49 UTC, weizhenwu approved these changes
LGTM

2023-07-12 15:32 UTC, merged