Add oem-qa-checkbox-installer
canonical/oem-qa-tools pull request #3
Opened 2023-03-09 10:13 UTC by LiaoU3

This is a tool to help us setup test environment and download checkbox.

2023-03-13 03:45 UTC, weizhenwu requested changes

2023-03-13 03:45 UTC, weizhenwu commented on Tools/PC/oem-qa-checkbox-installer/bin/install-packages.sh
> +echo ${pwd} | sudo apt install -y openssh-server
should we also enable it after the installation to make sure it's available?

2023-03-13 03:45 UTC, weizhenwu commented on Tools/PC/oem-qa-checkbox-installer/conf/plainbox.conf
> +TEST_TARGET_IPERF = 10.102.182.100, 10.102.182.137, 10.102.182.101, 10.102.182.48
Checkbox didn't handle the space so it will return "invalid address" while parsing " 10.102.182.137"

2023-03-13 04:06 UTC, weizhenwu commented on Tools/PC/oem-qa-checkbox-installer/conf/boxer.conf
> +repository = stable
Suggest having some directions on how to get this information(name/password/key/repo usage) in README or just comment here

2023-03-13 05:29 UTC, LiaoU3 commented on Tools/PC/oem-qa-checkbox-installer/conf/boxer.conf
> +repository = stable
Instructions added in README.

2023-03-13 05:30 UTC, LiaoU3 commented on Tools/PC/oem-qa-checkbox-installer/bin/install-packages.sh
> +echo ${pwd} | sudo apt install -y openssh-server
Even though it should be enable automatically, you are right! We should make sure that it is truly enabled.

2023-03-13 05:30 UTC, LiaoU3 commented on Tools/PC/oem-qa-checkbox-installer/conf/plainbox.conf
> +TEST_TARGET_IPERF = 10.102.182.100, 10.102.182.137, 10.102.182.101, 10.102.182.48
Fix.

2023-03-13 09:24 UTC, LiaoU3 commented on Tools/PC/oem-qa-checkbox-installer/oem-qa-checkbox-installer.sh
> +./bin/boxer.py
@baconYao Except here, when will we use boxer.py?

2023-03-13 09:26 UTC, LiaoU3 commented on Tools/PC/oem-qa-checkbox-installer/conf/plainbox.conf
> +TEST_TARGET_IPERF = 10.102.182.100, 10.102.182.137, 10.102.182.101, 10.102.182.48
Done

2023-03-13 10:55 UTC, weizhenwu commented
Hi @LiaoU3, may I know why you put Boxer as a class?
It seems to me have a boxer class is not quite meaningful, and a bit weird having a main function in the class as the main should be the entry point of the program

2023-03-13 13:50 UTC, weizhenwu requested changes

2023-03-13 13:50 UTC, weizhenwu commented on Tools/PC/oem-qa-checkbox-installer/bin/boxer.py
> +class Boxer():
if you want to package it as a class, then it's better to have a meaningful name instead of Boxer

2023-03-13 13:50 UTC, weizhenwu commented on Tools/PC/oem-qa-checkbox-installer/bin/boxer.py
> +    def main(self):
same as the class name, the function name should be meaningful as well.

2023-03-14 05:04 UTC, baconYao commented on Tools/PC/oem-qa-checkbox-installer/oem-qa-checkbox-installer.sh
> +./bin/boxer.py
Currently, no. Perhaps we can do this in the future. But I think there's few chances we leverage Boxer on IoT project, so it's also good to me for current sturcture.

2023-03-14 06:15 UTC, stanley31huang commented on Tools/PC/oem-qa-checkbox-installer/oem-qa-checkbox-installer.sh
> +./bin/boxer.py
I don't think we will uses boxer for an IoT project, since we install checkbox snap package instead of checkbox debian package.

2023-03-14 06:18 UTC, stanley31huang commented on Tools/PC/oem-qa-checkbox-installer/conf/boxer.conf
> +repository = stable
it would be better to separate this config into two sections likes...
```
[boxer]
username = yourname
ppa_password = ppapwd
provider = project pattern
repository = ppa channel

[c3]
username = yourname
api_key = yourapikey
```

2023-03-16 07:13 UTC, baconYao commented on Tools/PC/oem-qa-checkbox-installer/bin/get-id-info.py
> +f.close()
No need close while using with

2023-03-16 07:36 UTC, LiaoU3 commented on Tools/PC/oem-qa-checkbox-installer/bin/get-id-info.py
> +f.close()
@baconYao
Hi, this is the old script, I didn't change it. Because the main purpose for this PR is to migrate and refactor it. Actually there are several mistakes like this in boxer and old script. Maybe we could do it in the next PR? or you want me to do it in this PR?

2023-03-17 10:26 UTC, stanley31huang commented on Tools/PC/oem-qa-checkbox-installer/README.md
> +This is a tool to help you set up the test environment, like installing the main package `checkbox-cli`, and also other essential packages.
I think you are talking about checkbox-ng package, not checkbox-cli
checkbox-cli is a scripts in checkbox-ng package.

2023-03-17 10:27 UTC, stanley31huang commented on Tools/PC/oem-qa-checkbox-installer/README.md
> +# install_checkbox-provider
A minor suggestions here, it's a main topic here, so we could just uses "Install OEM Checkbox providers"

2023-03-17 10:33 UTC, stanley31huang requested changes
I have some concerns, please see my inline comments.
Thanks Vincent, we are almost make it a generic tools for all PC projects.

BTW, we could squash all of commits together while we merge the PR into master branch in the github website, I would suggest we send a single commit for the changes you made, so we could review the changes easily while you modify your scripts for any issues.

2023-03-17 16:26 UTC, LiaoU3 commented on Tools/PC/oem-qa-checkbox-installer/README.md
> +This is a tool to help you set up the test environment, like installing the main package `checkbox-cli`, and also other essential packages.
Done

2023-03-17 16:26 UTC, LiaoU3 commented on Tools/PC/oem-qa-checkbox-installer/bin/boxer.py
> +    provider = args.provider or boxercfg["provider"] or "sutton"
Done

2023-03-20 05:46 UTC, hanhsuan reviewed
Looks fine for me.

2023-03-20 07:40 UTC, baconYao approved these changes
LGTM

2023-03-21 00:01 UTC, hanhsuan approved these changes

2023-03-21 02:13 UTC, seankingyang approved these changes
LGTM~~

2023-03-21 02:26 UTC, weizhenwu approved these changes
LGTM

2023-03-21 02:33 UTC, merged