Create the new tool for creating testflinger yaml file
canonical/oem-qa-tools pull request #31
Opened 2023-07-24 02:11 UTC by seankingyang

Create the new tool for creating testflinger yaml file.
This tool is design for any if they want to using the testflinger to access/test the machine in cert lab.
(It also can be using for Lab4's machine, if we launch the agent first)

For some detail ref: https://warthogs.atlassian.net/browse/CQT-2814

2023-07-26 00:51 UTC, hanhsuan requested changes

2023-07-30 16:42 UTC, baconYao reviewed
Hi @seankingyang, I have some questions that need your help, thanks.

2023-07-30 16:42 UTC, baconYao commented on Tools/PC/testflinger_yaml_generator/readme.md
> +So the template struceture will like this:
`struceture` to `structure`

2023-07-30 16:42 UTC, baconYao commented on Tools/PC/testflinger_yaml_generator/readme.md
> +- Execute cmds files which will be include in test_cmds fields.
`include` to `included`

2023-07-30 16:42 UTC, baconYao commented on Tools/PC/testflinger_yaml_generator/readme.md
> +This script provide some argument for generating the yaml file:
`argument` to `arguments`

2023-07-30 16:42 UTC, baconYao commented on Tools/PC/testflinger_yaml_generator/template/bin/00initial
> +#!/bin/bash
May I know why the following lines not be the top of file
```
#!/bin/bash
# convenience functions
#
```

2023-07-30 16:42 UTC, baconYao commented on Tools/PC/testflinger_yaml_generator/template/bin/01dis_upgrade
> +_run sudo DEBIAN_FRONTEND=noninteractive apt-get -qq install -y
Need new line at the end.

2023-07-30 16:42 UTC, baconYao commented on Tools/PC/testflinger_yaml_generator/template/manifest.json
> +}
Need new line at the end.

2023-07-30 16:42 UTC, baconYao commented on Tools/PC/testflinger_yaml_generator/template/bin/02Install_checkbox_snap
> +_run sudo snap install checkbox --channel=latest/stable --classic
Need new line at the end.

2023-07-30 16:42 UTC, baconYao commented on Tools/PC/testflinger_yaml_generator/template/bin/02Install_checkbox_snap
> +_run sudo snap install checkbox20
Should we use `--beta` channel like what you did  `_run sudo add-apt-repository ppa:checkbox-dev/testing -y` in `02Install_checkbox_deb` file ?

2023-07-30 16:42 UTC, baconYao commented on Tools/PC/testflinger_yaml_generator/template/bin/90start_test
> +mkdir -p artifacts
Do we need to give the specific path for artifacts directory? Or it will be generated under the specific path since this script will be run at fixed path?

2023-07-30 16:42 UTC, baconYao commented on Tools/PC/testflinger_yaml_generator/template/bin/example_20before_test
> +_run sudo add-apt-repository \"deb https://warthogs:eB+uZWXE7@cesg.canonical.com/canonical somerville-fossa-psyduck-focal-staging public\" -y
I am afraid that these are sensitive information that we shouldn't expose to public repo.

2023-07-31 02:26 UTC, seankingyang commented on Tools/PC/testflinger_yaml_generator/template/bin/00initial
> +#!/bin/bash
The files in this folder should not be execute, and it's only like a text file will be merege in the testflinger yaml test command field.
The test flinger test command field will be parser and execute line by line.
Therefore I will not put the execute path for these files.

2023-07-31 02:30 UTC, seankingyang commented on Tools/PC/testflinger_yaml_generator/template/bin/02Install_checkbox_snap
> +_run sudo snap install checkbox20
For now this script should not run on checkbox snap version, bc it should provider the smart way to know if we need to install the checkbox20 or checkbox22.
This mechanism will be complete on next PR.

2023-07-31 02:32 UTC, seankingyang commented on Tools/PC/testflinger_yaml_generator/template/bin/90start_test
> +mkdir -p artifacts
The artifacts directory is under the working path on testflinger agent, and we should not change the working path in test flinger agent.

2023-07-31 02:34 UTC, seankingyang commented on Tools/PC/testflinger_yaml_generator/template/bin/example_20before_test
> +_run sudo add-apt-repository \"deb https://warthogs:eB+uZWXE7@cesg.canonical.com/canonical somerville-fossa-psyduck-focal-staging public\" -y
Oh... right, I will remove the sensitive info from this example script and replace it with our internal wiki link

2023-08-08 07:17 UTC, stanley31huang commented
I would suggest we move the divid_launcher contents as following
```
launcher_config
├── env
├── main
├── manifest
└── testplan
```

2023-08-08 08:00 UTC, seankingyang commented on Tools/PC/testflinger_yaml_generator/testflinger_ymal_generator.py
> +        TF_yaml_file_path = f"{args.outputFolder}/{args.outputFileName}.yaml"
Make it support this filename extention can be supported

2023-08-15 01:04 UTC, hanhsuan approved these changes
LGTM

2023-08-19 00:49 UTC, baconYao approved these changes
LGTM.

2023-08-21 05:43 UTC, merged

2023-08-21 05:43 UTC, stanley31huang commented
merged and closing