Add merge_test_matrix script to generate a test matrix file
canonical/oem-qa-tools pull request #33
Opened 2023-08-10 09:22 UTC by clairlin53

This script could be used to automate the process of generating test matrix from initial test results. It helps QA to procee the test scope for projects.

2023-08-13 02:50 UTC, baconYao requested changes
I don't think we need the `sample_test_matrix.xlsx` in repo, instead, we need some testing tarballs as golden testing data.

I suggest that we need a test_data directory which is used to store all the test tarballs.

2023-08-13 02:50 UTC, baconYao commented on Tools/PC/merge_test_matrix/README.md
> +1. place the tool and tarball files obtained from initial tests into the same folder.
Capital the first alphabet

2023-08-13 02:50 UTC, baconYao commented on Tools/PC/merge_test_matrix/merge_test_matrix.py
Looks like this script is migrated from https://git.launchpad.net/oem-qa-tools/tree/merge_test_matrix.py.
May I know is there any logical change of this script?

2023-08-14 06:30 UTC, clairlin53 commented
> I don't think we need the `sample_test_matrix.xlsx` in repo, instead, we need some testing tarballs as golden testing data.
> 
> I suggest that we need a test_data directory which is used to store all the test tarballs.

Tarbell file from the initial test result is based on the project, in my mind it's no meaning to put it here.

2023-08-15 14:29 UTC, baconYao commented
> > I don't think we need the `sample_test_matrix.xlsx` in repo, instead, we need some testing tarballs as golden testing data.
> > I suggest that we need a test_data directory which is used to store all the test tarballs.
> 
> Tarbell file from the initial test result is based on the project, in my mind it's no meaning to put it here.

Agree.
After discussing with Clair, there's no need to put any files such as sample xlsx or testing tarball in this tool.

2023-08-17 03:14 UTC, stanley31huang approved these changes
LGTM

2023-08-17 05:41 UTC, scotthu27 approved these changes
LGTM

2023-08-17 05:54 UTC, baconYao approved these changes
LGTM

2023-08-17 06:00 UTC, merged