Fix some bugs for applying OEMQA board
canonical/oem-qa-tools pull request #53
Opened 2023-12-01 07:20 UTC by baconYao

Fix bugs

- #50 
- #51 
- #52

2023-12-04 07:41 UTC, stanley31huang commented on API/Jira/scenarios/pc/pc.py
>              # FIXME: Use regex to verify the valid time format
could we remove all of marked code here?

2023-12-04 07:41 UTC, stanley31huang requested changes
please see my inline comments, thanks

2023-12-05 00:57 UTC, baconYao commented on API/Jira/scenarios/pc/pc.py
>              # FIXME: Use regex to verify the valid time format
Remove those comment block. Please check it again.

2023-12-06 02:31 UTC, weizhenwu approved these changes
LGTM

2023-12-06 05:01 UTC, stanley31huang approved these changes
LGTM

2023-12-11 03:24 UTC, merged