Fix: PR#61 #62 add valid number in the new lab6 and fix rack locations errors
canonical/oem-qa-tools pull request #63
Opened 2024-01-11 09:08 UTC by clairlin53

Add shelf, frame and partition number for valid location by
following structure specified in the Cert team's google sheet. 

Fix the error that exclude the rack location in parsing locations.

Issue:
https://github.com/canonical/oem-qa-tools/issues/61
https://github.com/canonical/oem-qa-tools/issues/62

2024-01-11 14:58 UTC, baconYao requested changes
See my inline comment

2024-01-11 14:58 UTC, baconYao commented on Tools/PC/transfer-hw-to-cert/utils/common.py
> +        r'L[6]-F\d{2}-S[1-8]-P[123])$'
Don't we need the `^TEL-` in front of line 20 & 21?

2024-01-12 02:01 UTC, clairlin53 commented on Tools/PC/transfer-hw-to-cert/utils/common.py
> +        r'L[6]-F\d{2}-S[1-8]-P[123])$'
Let me show you the original one, it's easy to see.
`r'^TEL-(L\d-R\d{2}-S\d{1,2}-P[0-1]|L[35]-F\d{2}-S[1-5]-P[12]|L[67]-F\d{2}-S[1-8]-P[123])$'`
Because of the initial "^TEL-".
To accommodate character limitations, the regular expression is split across three lines for improved readability.

2024-01-12 02:40 UTC, baconYao commented on Tools/PC/transfer-hw-to-cert/utils/common.py
> +        r'L[6]-F\d{2}-S[1-8]-P[123])$'
Oh my bad.

2024-01-12 02:41 UTC, baconYao approved these changes
LGTM

2024-01-12 05:39 UTC, stanley31huang commented on Tools/PC/transfer-hw-to-cert/utils/common.py
> +        r'L[6]-F\d{2}-S[1-8]-P[123])$'
I think we could simply create two rules, one for RACK another one for Frame

2024-01-12 06:16 UTC, stanley31huang approved these changes
LGTM

2024-01-12 06:22 UTC, merged