Add plainbox-provider-pc-sanity and install checkbox on agent
canonical/oem-qa-tools pull request #70
Opened 2024-07-11 05:39 UTC by Artur-at-work

**Changes:**
1. Added plainbox-provider-pc-sanity in templates to be installed on DUT
2. Added template to install checkbox-ng on agent, then switch to specific version to match with DUT. This code was copied from Cert team Jenkins and adjusted to agent env.
3. Use "control" instead of "remote"

Above changes are expected in infrastructure-checkbox-run job.

**Test:**
- Run shellcheck against new templates
- Run infrastructure-checkbox-run job (Note: there are some errors when switching checkbox version, but the same errors are found in cert teams SRU job. So I assume those are not relevant)

2024-07-11 06:33 UTC, seankingyang approved these changes
LGTM~~

2024-07-11 06:33 UTC, seankingyang commented on Tools/PC/testflinger_yaml_generator/template/shell_scripts/90_start_test
> +PYTHONUNBUFFERED=1 checkbox-cli control "$DEVICE_IP" checkbox-launcher
Thank for correct this ~~

2024-07-11 06:33 UTC, seankingyang commented on Tools/PC/testflinger_yaml_generator/template/shell_scripts/02_Install_checkbox_deb
> +_run sudo DEBIAN_FRONTEND=noninteractive apt-get install checkbox-provider-base checkbox-ng checkbox-provider-resource checkbox-provider-certification-client plainbox-provider-pc-sanity -y
`plainbox-provider-pc-sanity` seems in https://ppa.launchpadcontent.net/checkbox-dev/beta/ubuntu.

2024-07-11 06:59 UTC, hanhsuan requested changes

2024-07-11 06:59 UTC, hanhsuan commented on Tools/PC/testflinger_yaml_generator/template/shell_scripts/15_install_checkbox_on_agent
> +if [ "False" == False ]; then
Could we add some information to let user or maintainer know that `"False == False"` means that we always use debian version checkbox and provide some flexibility to modify to support snap in the future?

2024-07-12 01:58 UTC, Artur-at-work commented on Tools/PC/testflinger_yaml_generator/template/shell_scripts/15_install_checkbox_on_agent
> +if [ "False" == False ]; then
The "false== false" check was removed. Since generator decides the config for deb/snap a step earlier, we can initialize the CHECKBOX_CLI_CMD there, so it will always pick the right version.
Uploaded the changes. Please help to review again.

2024-07-12 02:00 UTC, hanhsuan approved these changes
LGTM

2024-07-12 02:29 UTC, merged