Some helper scripts for reading C3 submissions
canonical/oem-qa-tools pull request #74
Opened 2024-08-19 03:26 UTC by tomli380576

2024-09-09 09:21 UTC, stanley31huang commented on Tools/PC/c3-submission-helpers/README.md
> +- `python3 parse-suspend-30-logs.py -f path/to/submission-202408-12345.tar`
the file extension should be `tar.xz`?

2024-09-09 09:34 UTC, stanley31huang commented on Tools/PC/c3-submission-helpers/parse-suspend-30-logs.py
> +            if SECTION_BEGIN not in line:
Is it possible to split the logs by `lines.split(SECTION_BEGIN)`? Or there's a special reason that we need to read the log line by line?

2024-09-10 03:11 UTC, tomli380576 commented on Tools/PC/c3-submission-helpers/parse-suspend-30-logs.py
> +            if SECTION_BEGIN not in line:
You can't split a `list` unfortunately. But that did give me an idea: https://stackoverflow.com/questions/7980288/splitting-large-text-file-by-a-delimiter-in-python

So instead of keeping the entire file in memory, we only need 1 section at a time

2024-09-10 03:11 UTC, tomli380576 commented on Tools/PC/c3-submission-helpers/README.md
> +- `python3 parse-suspend-30-logs.py -f path/to/submission-202408-12345.tar`
Loll thanks for catching that

2024-09-27 13:08 UTC, baconYao reviewed
The discussion of `FailType`

2024-09-27 13:08 UTC, baconYao commented on Tools/PC/c3-submission-helpers/parse-suspend-30-logs.py
> +        failed_runs_by_type: dict[FailType, list] = {
```suggestion
        failed_runs_by_type: dict[Literal[*FailType], list] = {
```

2024-09-27 13:08 UTC, baconYao commented on Tools/PC/c3-submission-helpers/parse-suspend-30-logs.py
> +                for fail_type in "Critical", "High", "Medium", "Low", "Other":
```suggestion
                for fail_type in FailType:
```

2024-09-30 02:07 UTC, tomli380576 commented on Tools/PC/c3-submission-helpers/parse-suspend-30-logs.py
> +        failed_runs_by_type: dict[FailType, list] = {
omg ty I can finally have the python equivalent of this :sob:

![Screenshot from 2024-09-30 10-06-34](https://github.com/user-attachments/assets/45cf3a05-302a-4ecd-acdc-0501b9144c7a)

2024-12-17 08:47 UTC, seankingyang requested changes
These scripts are very usefull.
Only one thing need to update, please update the usage in README.md.
The README.md is seem not like the newest version.
Also mention the difference between better-cbwb-differs.py , cbwb-diffs.py, summarize-reboot-check-test.py. As I know one of the script is only can be used in the old cb/wb output which was run by the reboot_check.sh.

2024-12-23 02:46 UTC, tomli380576 commented
gonna add all the remaining tests while I'm at it. currently it only shows fwts and device comparison results

2024-12-24 08:23 UTC, tomli380576 commented
will prob refactor this a bit more but functionality wise everything is there

2025-02-14 03:27 UTC, tomli380576 commented
it also summarizes device diff now

2025-03-05 05:24 UTC, seankingyang requested changes
I left a tinny comment at bellow.
Please check it

2025-03-05 05:24 UTC, seankingyang commented on Tools/PC/c3-submission-helpers/summarize-reboot-check-test.py
> +
Could you add some comments in this script to descript this parser is relate with https://github.com/canonical/checkbox/blob/main/providers/base/bin/reboot_check_test.py?
It will be easier for others know if there is any change in `reboot_check_test.py`, this script will also need to modify.

2025-03-05 05:47 UTC, seankingyang approved these changes
LGTM~~
Thank you~~

2025-03-05 05:48 UTC, merged