testflinger-yaml-generator: add provision parameters for oem_autoinstall connector
canonical/oem-qa-tools pull request #76
Opened 2024-08-21 06:12 UTC by Artur-at-work

Expand tf-yaml-generator to support [oem_autoinstall device connector](https://github.com/canonical/testflinger/pull/304) in 24.04.
It adds 3 more parameters + attachments in the provision stage of job.yaml. These parameters are optional, so if args not added, then no changes to original behavior and templates.

Sample provisioning data for 24.04:

```
job_queue: artur-oemscript-2404
provision_data:
  url: http://10.131.60.220:8080/job/somerville-noble-oem-24.04a/lastSuccessfulBuild/artifact/out/somerville-noble-oem-24.04a-20240806-59.iso
  token_file: "jenkins-token.txt"
  user_data: "ubuntu-oem-image-builder/alloem-init/cloud-configs/redeploy/user-data"
  authorized_keys: "ubuntu-oem-image-builder/injections/alloem-init/chroot/minimal.standard.live.hotfix.squashfs/etc/ssh/authorized_keys"
  attachments:
    - local: "ubuntu-oem-image-builder/alloem-init/cloud-configs/redeploy/user-data"
    - local: "ubuntu-oem-image-builder/injections/alloem-init/chroot/minimal.standard.live.hotfix.squashfs/etc/ssh/authorized_keys"
    - local: "jenkins-token.txt"
```

2024-08-21 14:38 UTC, Artur-at-work commented
hi @seankingyang , could you help to review please? 
It seems I can't request the reviewers directly..

2024-08-22 03:37 UTC, seankingyang requested changes
Thanks for this great changing, and there are some suggestions at below

2024-08-22 03:37 UTC, seankingyang commented on Tools/PC/testflinger_yaml_generator/testflinger_yaml_generator.py
> +                          URL auth')
Could add more detail in the help and  give the sample on it?
ie File with username and token for Jenkins image url auth, and it will be the yaml format.
ie. [$JENKINS_USERNAME]\n token = $JENKINS_API_TOKEN

2024-08-22 03:37 UTC, seankingyang commented on Tools/PC/testflinger_yaml_generator/testflinger_yaml_generator.py
> +                          provisioning')
Could you give the sample file or the link to let us know how to write it?
Add the help info `This argument is MUST required if deploy the image using the autoinstall image (ie. 24.04 image)`

2024-08-22 03:37 UTC, seankingyang commented on Tools/PC/testflinger_yaml_generator/testflinger_yaml_generator.py
> +                          system')
change the help info to `ssh authorized_keys file to add in provisioned system`

2024-08-23 06:03 UTC, Artur-at-work commented on Tools/PC/testflinger_yaml_generator/testflinger_yaml_generator.py
> +                          system')
Thank you for the feedback. I've updated as requested.
Also, Testflinger documentation will have the user-data example for reference.

2024-08-23 06:04 UTC, Artur-at-work commented
@seankingyang Thank you for the feedback. I've updated as requested.
Also, Testflinger documentation will have the user-data example for reference.

2024-08-23 08:41 UTC, seankingyang approved these changes

2024-08-23 08:41 UTC, merged